disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple

opt_in_rules:
  - empty_count
  - force_unwrapping

excluded:
  - Pods
  - DerivedData
  - .build

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 500
  error: 800

identifier_name:
  min_length: 1
  max_length: 60

reporter: "xcode"
